#!/usr/bin/env python3
"""
Import products, brands, and categories to database from JSON file.

Usage:
    python import_to_db.py /path/to/import_data.json

The JSON file should be generated by generate_and_upload.py
"""

import sys
import json
import psycopg2
from datetime import datetime, timezone

# Database configuration
DB_URL = "postgresql://postgres:it is me@localhost:5432/elsuq"


def get_or_create_brand(cur, brand_data):
    """Get existing brand ID or create new one."""
    cur.execute("SELECT id FROM brands WHERE LOWER(name) = LOWER(%s)", (brand_data['name'],))
    result = cur.fetchone()
    if result:
        print(f"  Brand exists: {brand_data['name']} (ID: {result[0]})")
        return result[0]

    cur.execute("""
        INSERT INTO brands (name, name_translations, is_active, created_at)
        VALUES (%s, %s, %s, %s)
        RETURNING id
    """, (
        brand_data['name'],
        json.dumps(brand_data['name_translations']),
        brand_data['is_active'],
        datetime.now(timezone.utc)
    ))
    brand_id = cur.fetchone()[0]
    print(f"  Created brand: {brand_data['name']} (ID: {brand_id})")
    return brand_id


def get_or_create_category(cur, category_data):
    """Get existing category ID or create new one."""
    cur.execute("SELECT id FROM categories WHERE LOWER(name) = LOWER(%s)", (category_data['name'],))
    result = cur.fetchone()
    if result:
        print(f"  Category exists: {category_data['name']} (ID: {result[0]})")
        return result[0]

    cur.execute("""
        INSERT INTO categories (name, name_translations, is_active, created_at)
        VALUES (%s, %s, %s, %s)
        RETURNING id
    """, (
        category_data['name'],
        json.dumps(category_data['name_translations']),
        category_data['is_active'],
        datetime.now(timezone.utc)
    ))
    category_id = cur.fetchone()[0]
    print(f"  Created category: {category_data['name']} (ID: {category_id})")
    return category_id


def create_product(cur, product, brand_id, category_id):
    """Create a product in the database."""
    cur.execute("""
        INSERT INTO products (
            name, description, name_translations, description_translations,
            price, unit, stock_quantity, image_url, is_organic, is_active,
            category_id, brand_id, pieces_per_box, packaging_type, created_at
        ) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
        RETURNING id
    """, (
        product['name'],
        product['description'],
        json.dumps(product['name_translations']),
        json.dumps(product['description_translations']),
        product['price'],
        product['unit'],
        product['stock_quantity'],
        product['image_url'],
        product['is_organic'],
        product['is_active'],
        category_id,
        brand_id,
        product['pieces_per_box'],
        product['packaging_type'],
        datetime.now(timezone.utc)
    ))
    return cur.fetchone()[0]


def main():
    if len(sys.argv) < 2:
        print(__doc__)
        sys.exit(1)

    json_file = sys.argv[1]

    # Load data
    print(f"Loading {json_file}...")
    with open(json_file, 'r', encoding='utf-8') as f:
        data = json.load(f)

    # Connect to database
    conn = psycopg2.connect(DB_URL)
    cur = conn.cursor()

    print("\n" + "=" * 50)
    print("Creating brands...")
    brand_ids = {}
    for brand in data['brands']:
        brand_ids[brand['name']] = get_or_create_brand(cur, brand)

    print("\n" + "=" * 50)
    print("Creating categories...")
    category_ids = {}
    for category in data['categories']:
        category_ids[category['name']] = get_or_create_category(cur, category)

    print("\n" + "=" * 50)
    print("Creating products...")
    created = 0
    for product in data['products']:
        brand_id = brand_ids.get(product['brand'])
        category_id = category_ids.get(product['category'])

        if not brand_id:
            print(f"  WARNING: Brand '{product['brand']}' not found, skipping {product['name']}")
            continue
        if not category_id:
            print(f"  WARNING: Category '{product['category']}' not found, skipping {product['name']}")
            continue

        product_id = create_product(cur, product, brand_id, category_id)
        print(f"  Created: {product['name']} (ID: {product_id})")
        created += 1

    # Commit
    conn.commit()
    cur.close()
    conn.close()

    print("\n" + "=" * 50)
    print(f"Import complete!")
    print(f"  - {len(brand_ids)} brands")
    print(f"  - {len(category_ids)} categories")
    print(f"  - {created} products")


if __name__ == "__main__":
    main()
