# backend/app/seed_test_users.py
"""
Seed script for test users: drivers, customers, and staff.
Real store locations in Ouadhia daira, Tizi Ouzou wilaya.
"""
import logging
from sqlmodel import Session, select
from app.database import engine
from app.models.user import User, UserRole, AuthProvider
from app.models.driver import Driver, DriverVehicle, VehicleType, DriverStatus
from app.core.security import get_password_hash

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

# Store center coordinates (Ouadhia, Tizi Ouzou)
STORE_CENTER_LAT = 36.549608
STORE_CENTER_LNG = 4.099945

# Default password for all test users
DEFAULT_PASSWORD = "test1234"

# Test users data with REAL store locations
TEST_USERS = [
    # ==================== DRIVERS ====================
    {
        "email": "driver1@test.com",
        "full_name": "Chabane Melab",
        "phone": "0555123401",
        "store_name": None,
        "role": UserRole.DRIVER,
        "h3_index": "893874c6143ffff",
        "address": "12 Rue Principale, Ouadhia Centre",
        "wilaya": "Tizi Ouzou",
        "daira": "Ouadhia",
        "commune": "Ouadhia",
        "latitude": 36.5560,
        "longitude": 4.0860,
        "driver_data": {
            "status": DriverStatus.AVAILABLE,
            "is_available": True,
            "max_active_orders": 5,
        },
        "vehicle_data": {
            "vehicle_type": VehicleType.TRUCK,
            "capacity_kg": 30000.0,
            "capacity_volume": 50.0,
        }
    },
    {
        "email": "driver2@test.com",
        "full_name": "Youcef Mammeri",
        "phone": "0555123402",
        "store_name": None,
        "role": UserRole.DRIVER,
        "h3_index": "893874c6143ffff",
        "address": "45 Route de Tizi N'Tlata, Agouni Gueghrane",
        "wilaya": "Tizi Ouzou",
        "daira": "Ouadhia",
        "commune": "Agouni Gueghrane",
        "latitude": 36.5245,
        "longitude": 4.1217,
        "driver_data": {
            "status": DriverStatus.AVAILABLE,
            "is_available": True,
            "max_active_orders": 3,
        },
        "vehicle_data": {
            "vehicle_type": VehicleType.VAN,
            "capacity_kg": 18000.0,
            "capacity_volume": 30.0,
        }
    },
    {
        "email": "driver3@test.com",
        "full_name": "Omar Hadj",
        "phone": "0555123403",
        "store_name": None,
        "role": UserRole.DRIVER,
        "h3_index": "8938748b137ffff",
        "address": "8 Rue des Oliviers, Ait Bouadou",
        "wilaya": "Tizi Ouzou",
        "daira": "Ouadhia",
        "commune": "Ait Bouadou",
        "latitude": 36.5380,
        "longitude": 4.0620,
        "driver_data": {
            "status": DriverStatus.OFFLINE,
            "is_available": False,
            "max_active_orders": 2,
        },
        "vehicle_data": {
            "vehicle_type": VehicleType.MINI_VAN,
            "capacity_kg": 7000.0,
            "capacity_volume": 12.0,
        }
    },

    # ==================== ZONE A: AGOUNI GUEGHRANE (9 stores) ====================
    {
        "email": "djafer.mekhtoub@test.com",
        "full_name": "Djafer Mekhtoub",
        "phone": "0555201001",
        "store_name": "Alimentation 4 Chemins",
        "role": UserRole.CUSTOMER,
        "h3_index": "8938748b137ffff",
        "address": "4 Chemins, Agouni Gueghrane",
        "wilaya": "Tizi Ouzou",
        "daira": "Ouadhia",
        "commune": "Agouni Gueghrane",
        "latitude": 36.524619,
        "longitude": 4.121721,
    },
    {
        "email": "mesrouk.malik@test.com",
        "full_name": "Mesrouk Malik",
        "phone": "0555201002",
        "store_name": "Epicerie Mesrouk",
        "role": UserRole.CUSTOMER,
        "h3_index": "8938748b137ffff",
        "address": "Centre, Agouni Gueghrane",
        "wilaya": "Tizi Ouzou",
        "daira": "Ouadhia",
        "commune": "Agouni Gueghrane",
        "latitude": 36.524641,
        "longitude": 4.122199,
    },
    {
        "email": "assam.moumouh@test.com",
        "full_name": "Assam Moumouh",
        "phone": "0555201003",
        "store_name": "Alimentation Moumouh",
        "role": UserRole.CUSTOMER,
        "h3_index": "8938748b137ffff",
        "address": "Route Principale, Agouni Gueghrane",
        "wilaya": "Tizi Ouzou",
        "daira": "Ouadhia",
        "commune": "Agouni Gueghrane",
        "latitude": 36.515231,
        "longitude": 4.114196,
    },
    {
        "email": "amar.bota@test.com",
        "full_name": "Amar Bota",
        "phone": "0555201004",
        "store_name": "Superette Bota",
        "role": UserRole.CUSTOMER,
        "h3_index": "8938748b137ffff",
        "address": "Quartier Sud, Agouni Gueghrane",
        "wilaya": "Tizi Ouzou",
        "daira": "Ouadhia",
        "commune": "Agouni Gueghrane",
        "latitude": 36.515073,
        "longitude": 4.114843,
    },
    {
        "email": "djafer.mekhtoub2@test.com",
        "full_name": "Djafer Mekhtoub",
        "phone": "0555201005",
        "store_name": "Alimentation Mekhtoub",
        "role": UserRole.CUSTOMER,
        "h3_index": "8938748b137ffff",
        "address": "Bas Quartier, Agouni Gueghrane",
        "wilaya": "Tizi Ouzou",
        "daira": "Ouadhia",
        "commune": "Agouni Gueghrane",
        "latitude": 36.514562,
        "longitude": 4.122369,
    },
    {
        "email": "melaz.nourdine@test.com",
        "full_name": "Melaz Nourdine",
        "phone": "0555201006",
        "store_name": "Mini Market Melaz",
        "role": UserRole.CUSTOMER,
        "h3_index": "8938748b137ffff",
        "address": "Quartier Est, Agouni Gueghrane",
        "wilaya": "Tizi Ouzou",
        "daira": "Ouadhia",
        "commune": "Agouni Gueghrane",
        "latitude": 36.514580,
        "longitude": 4.123209,
    },
    {
        "email": "menad@test.com",
        "full_name": "Menad",
        "phone": "0555201007",
        "store_name": "Epicerie Menad",
        "role": UserRole.CUSTOMER,
        "h3_index": "8938748b137ffff",
        "address": "Route de Ouadhia, Agouni Gueghrane",
        "wilaya": "Tizi Ouzou",
        "daira": "Ouadhia",
        "commune": "Agouni Gueghrane",
        "latitude": 36.528152,
        "longitude": 4.129180,
    },
    {
        "email": "bedrane.amirouche@test.com",
        "full_name": "Bedrane Amirouche",
        "phone": "0555201008",
        "store_name": "Alimentation Bedrane",
        "role": UserRole.CUSTOMER,
        "h3_index": "8938748b137ffff",
        "address": "Quartier Nord, Agouni Gueghrane",
        "wilaya": "Tizi Ouzou",
        "daira": "Ouadhia",
        "commune": "Agouni Gueghrane",
        "latitude": 36.529932,
        "longitude": 4.118298,
    },
    {
        "email": "moukah@test.com",
        "full_name": "Moukah",
        "phone": "0555201009",
        "store_name": "Superette Moukah",
        "role": UserRole.CUSTOMER,
        "h3_index": "8938748b137ffff",
        "address": "Sortie Nord, Agouni Gueghrane",
        "wilaya": "Tizi Ouzou",
        "daira": "Ouadhia",
        "commune": "Agouni Gueghrane",
        "latitude": 36.531827,
        "longitude": 4.115533,
    },

    # ==================== ZONE B: OUADHIA CENTRE (12 stores) ====================
    {
        "email": "hopital@test.com",
        "full_name": "Superette Hôpital",
        "phone": "0555202001",
        "store_name": "Superette Hôpital",
        "role": UserRole.CUSTOMER,
        "h3_index": "893874c6143ffff",
        "address": "Près de l'Hôpital, Ouadhia",
        "wilaya": "Tizi Ouzou",
        "daira": "Ouadhia",
        "commune": "Ouadhia",
        "latitude": 36.543181,
        "longitude": 4.104670,
    },
    {
        "email": "client.ouadhia1@test.com",
        "full_name": "Karim Belhadj",
        "phone": "0555202002",
        "store_name": "Alimentation Belhadj",
        "role": UserRole.CUSTOMER,
        "h3_index": "893874c6143ffff",
        "address": "Route de l'Hôpital, Ouadhia",
        "wilaya": "Tizi Ouzou",
        "daira": "Ouadhia",
        "commune": "Ouadhia",
        "latitude": 36.548411,
        "longitude": 4.102103,
    },
    {
        "email": "ali.ouremdhane@test.com",
        "full_name": "Ali Ou Remdhane",
        "phone": "0555202003",
        "store_name": "Epicerie Ali",
        "role": UserRole.CUSTOMER,
        "h3_index": "893874c6143ffff",
        "address": "Centre Ville, Ouadhia",
        "wilaya": "Tizi Ouzou",
        "daira": "Ouadhia",
        "commune": "Ouadhia",
        "latitude": 36.552084,
        "longitude": 4.097189,
    },
    {
        "email": "superette.juba@test.com",
        "full_name": "Superette Juba",
        "phone": "0555202004",
        "store_name": "Superette Juba",
        "role": UserRole.CUSTOMER,
        "h3_index": "893874c6143ffff",
        "address": "Rue Principale, Ouadhia",
        "wilaya": "Tizi Ouzou",
        "daira": "Ouadhia",
        "commune": "Ouadhia",
        "latitude": 36.552980,
        "longitude": 4.097259,
    },
    {
        "email": "client.ouadhia2@test.com",
        "full_name": "Rachid Ait Kaci",
        "phone": "0555202005",
        "store_name": "Mini Market Ait Kaci",
        "role": UserRole.CUSTOMER,
        "h3_index": "893874c6143ffff",
        "address": "Quartier Central, Ouadhia",
        "wilaya": "Tizi Ouzou",
        "daira": "Ouadhia",
        "commune": "Ouadhia",
        "latitude": 36.554413,
        "longitude": 4.095718,
    },
    {
        "email": "client.ouadhia3@test.com",
        "full_name": "Samir Bouziane",
        "phone": "0555202006",
        "store_name": "Alimentation Bouziane",
        "role": UserRole.CUSTOMER,
        "h3_index": "893874c6143ffff",
        "address": "Route Est, Ouadhia",
        "wilaya": "Tizi Ouzou",
        "daira": "Ouadhia",
        "commune": "Ouadhia",
        "latitude": 36.555655,
        "longitude": 4.108690,
    },
    {
        "email": "client.ouadhia4@test.com",
        "full_name": "Farid Hamiche",
        "phone": "0555202007",
        "store_name": "Epicerie Hamiche",
        "role": UserRole.CUSTOMER,
        "h3_index": "893874c6143ffff",
        "address": "Quartier Est, Ouadhia",
        "wilaya": "Tizi Ouzou",
        "daira": "Ouadhia",
        "commune": "Ouadhia",
        "latitude": 36.555685,
        "longitude": 4.121689,
    },
    {
        "email": "client.ouadhia5@test.com",
        "full_name": "Nabil Cherifi",
        "phone": "0555202008",
        "store_name": "Superette Cherifi",
        "role": UserRole.CUSTOMER,
        "h3_index": "893874c6143ffff",
        "address": "Sortie Est, Ouadhia",
        "wilaya": "Tizi Ouzou",
        "daira": "Ouadhia",
        "commune": "Ouadhia",
        "latitude": 36.555574,
        "longitude": 4.131805,
    },
    {
        "email": "client.ouadhia6@test.com",
        "full_name": "Hakim Slimani",
        "phone": "0555202009",
        "store_name": "Alimentation Slimani",
        "role": UserRole.CUSTOMER,
        "h3_index": "893874c6143ffff",
        "address": "Rue du Marché, Ouadhia",
        "wilaya": "Tizi Ouzou",
        "daira": "Ouadhia",
        "commune": "Ouadhia",
        "latitude": 36.555517,
        "longitude": 4.090195,
    },
    {
        "email": "metarfi@test.com",
        "full_name": "Metarfi",
        "phone": "0555202010",
        "store_name": "Epicerie Metarfi",
        "role": UserRole.CUSTOMER,
        "h3_index": "893874c6143ffff",
        "address": "Centre, Ouadhia",
        "wilaya": "Tizi Ouzou",
        "daira": "Ouadhia",
        "commune": "Ouadhia",
        "latitude": 36.556073,
        "longitude": 4.089829,
    },
    {
        "email": "superette.azem@test.com",
        "full_name": "Superette Azem",
        "phone": "0555202011",
        "store_name": "Superette Azem",
        "role": UserRole.CUSTOMER,
        "h3_index": "893874c6143ffff",
        "address": "Rue Principale, Ouadhia",
        "wilaya": "Tizi Ouzou",
        "daira": "Ouadhia",
        "commune": "Ouadhia",
        "latitude": 36.555321,
        "longitude": 4.089005,
    },
    {
        "email": "arret.tizi@test.com",
        "full_name": "Superette Arrêt Tizi Ouzou",
        "phone": "0555202012",
        "store_name": "Superette Arrêt Tizi Ouzou",
        "role": UserRole.CUSTOMER,
        "h3_index": "893874c6143ffff",
        "address": "Arrêt Bus Tizi Ouzou, Ouadhia",
        "wilaya": "Tizi Ouzou",
        "daira": "Ouadhia",
        "commune": "Ouadhia",
        "latitude": 36.555414,
        "longitude": 4.087765,
    },

    # ==================== ZONE C: OUADHIA - Additional stores (moved from Tizi N'Tlata) ====================
    {
        "email": "client.ouadhia7@test.com",
        "full_name": "Yacine Ould Ali",
        "phone": "0555203001",
        "store_name": "Alimentation Ould Ali",
        "role": UserRole.CUSTOMER,
        "h3_index": "893874c6143ffff",
        "address": "Quartier Nord, Ouadhia",
        "wilaya": "Tizi Ouzou",
        "daira": "Ouadhia",
        "commune": "Ouadhia",
        "latitude": 36.554447,
        "longitude": 4.087460,
    },
    {
        "email": "client.ouadhia8@test.com",
        "full_name": "Mourad Benali",
        "phone": "0555203002",
        "store_name": "Epicerie Benali",
        "role": UserRole.CUSTOMER,
        "h3_index": "893874c6143ffff",
        "address": "Quartier Sud-Ouest, Ouadhia",
        "wilaya": "Tizi Ouzou",
        "daira": "Ouadhia",
        "commune": "Ouadhia",
        "latitude": 36.549528,
        "longitude": 4.084663,
    },
    {
        "email": "client.ouadhia9@test.com",
        "full_name": "Lyes Haddad",
        "phone": "0555203003",
        "store_name": "Superette Haddad",
        "role": UserRole.CUSTOMER,
        "h3_index": "893874c6143ffff",
        "address": "Sortie Nord, Ouadhia",
        "wilaya": "Tizi Ouzou",
        "daira": "Ouadhia",
        "commune": "Ouadhia",
        "latitude": 36.557120,
        "longitude": 4.086477,
    },
    {
        "email": "client.ouadhia10@test.com",
        "full_name": "Sofiane Mohand",
        "phone": "0555203004",
        "store_name": "Mini Market Mohand",
        "role": UserRole.CUSTOMER,
        "h3_index": "893874c6143ffff",
        "address": "Route Nord, Ouadhia",
        "wilaya": "Tizi Ouzou",
        "daira": "Ouadhia",
        "commune": "Ouadhia",
        "latitude": 36.556495,
        "longitude": 4.085345,
    },
    {
        "email": "client.ouadhia11@test.com",
        "full_name": "Nassim Kaci",
        "phone": "0555203005",
        "store_name": "Alimentation Kaci",
        "role": UserRole.CUSTOMER,
        "h3_index": "893874c6143ffff",
        "address": "Place Secondaire, Ouadhia",
        "wilaya": "Tizi Ouzou",
        "daira": "Ouadhia",
        "commune": "Ouadhia",
        "latitude": 36.555530,
        "longitude": 4.085023,
    },
    {
        "email": "client.ouadhia12@test.com",
        "full_name": "Arezki Brahimi",
        "phone": "0555203006",
        "store_name": "Epicerie Brahimi",
        "role": UserRole.CUSTOMER,
        "h3_index": "893874c6143ffff",
        "address": "Quartier Ouest, Ouadhia",
        "wilaya": "Tizi Ouzou",
        "daira": "Ouadhia",
        "commune": "Ouadhia",
        "latitude": 36.554390,
        "longitude": 4.082734,
    },
    {
        "email": "client.ouadhia13@test.com",
        "full_name": "Kamel Ziane",
        "phone": "0555203007",
        "store_name": "Superette Ziane",
        "role": UserRole.CUSTOMER,
        "h3_index": "893874c6143ffff",
        "address": "Route de Boghni, Ouadhia",
        "wilaya": "Tizi Ouzou",
        "daira": "Ouadhia",
        "commune": "Ouadhia",
        "latitude": 36.553453,
        "longitude": 4.080286,
    },
    {
        "email": "client.ouadhia14@test.com",
        "full_name": "Toufik Idir",
        "phone": "0555203008",
        "store_name": "Alimentation Idir",
        "role": UserRole.CUSTOMER,
        "h3_index": "893874c6143ffff",
        "address": "Sortie Ouest, Ouadhia",
        "wilaya": "Tizi Ouzou",
        "daira": "Ouadhia",
        "commune": "Ouadhia",
        "latitude": 36.551181,
        "longitude": 4.075279,
    },

    # ==================== ZONE D: TIZI N'TLATA (7 stores) ====================
    {
        "email": "client.tizintlata1@test.com",
        "full_name": "Mouloud Ait Saada",
        "phone": "0555204001",
        "store_name": "Epicerie Ait Saada",
        "role": UserRole.CUSTOMER,
        "h3_index": "89387417647ffff",
        "address": "Centre, Tizi N'Tlata",
        "wilaya": "Tizi Ouzou",
        "daira": "Ouadhia",
        "commune": "Tizi N'Tlata",
        "latitude": 36.549282,
        "longitude": 4.065949,
    },
    {
        "email": "client.tizintlata2@test.com",
        "full_name": "Smail Amrouche",
        "phone": "0555204002",
        "store_name": "Mini Market Amrouche",
        "role": UserRole.CUSTOMER,
        "h3_index": "89387417647ffff",
        "address": "Route Principale, Tizi N'Tlata",
        "wilaya": "Tizi Ouzou",
        "daira": "Ouadhia",
        "commune": "Tizi N'Tlata",
        "latitude": 36.548180,
        "longitude": 4.061165,
    },
    {
        "email": "client.tizintlata3@test.com",
        "full_name": "Rabah Ouali",
        "phone": "0555204003",
        "store_name": "Alimentation Ouali",
        "role": UserRole.CUSTOMER,
        "h3_index": "89387417647ffff",
        "address": "Quartier Sud, Tizi N'Tlata",
        "wilaya": "Tizi Ouzou",
        "daira": "Ouadhia",
        "commune": "Tizi N'Tlata",
        "latitude": 36.543975,
        "longitude": 4.059092,
    },
    {
        "email": "client.tizintlata4@test.com",
        "full_name": "Farida Meziane",
        "phone": "0555204004",
        "store_name": "Superette Meziane",
        "role": UserRole.CUSTOMER,
        "h3_index": "89387417647ffff",
        "address": "Quartier Ouest, Tizi N'Tlata",
        "wilaya": "Tizi Ouzou",
        "daira": "Ouadhia",
        "commune": "Tizi N'Tlata",
        "latitude": 36.545387,
        "longitude": 4.056007,
    },
    {
        "email": "client.tizintlata5@test.com",
        "full_name": "Nadia Taleb",
        "phone": "0555204005",
        "store_name": "Epicerie Taleb",
        "role": UserRole.CUSTOMER,
        "h3_index": "89387417647ffff",
        "address": "Place du Village, Tizi N'Tlata",
        "wilaya": "Tizi Ouzou",
        "daira": "Ouadhia",
        "commune": "Tizi N'Tlata",
        "latitude": 36.543661,
        "longitude": 4.056915,
    },
    {
        "email": "client.tizintlata6@test.com",
        "full_name": "Djamel Belkacem",
        "phone": "0555204006",
        "store_name": "Mini Market Belkacem",
        "role": UserRole.CUSTOMER,
        "h3_index": "89387417647ffff",
        "address": "Sortie Ouest, Tizi N'Tlata",
        "wilaya": "Tizi Ouzou",
        "daira": "Ouadhia",
        "commune": "Tizi N'Tlata",
        "latitude": 36.548076,
        "longitude": 4.055244,
    },
    {
        "email": "client.tizintlata7@test.com",
        "full_name": "Lynda Oukaci",
        "phone": "0555204007",
        "store_name": "Alimentation Oukaci",
        "role": UserRole.CUSTOMER,
        "h3_index": "89387417647ffff",
        "address": "Route de Boghni, Tizi N'Tlata",
        "wilaya": "Tizi Ouzou",
        "daira": "Ouadhia",
        "commune": "Tizi N'Tlata",
        "latitude": 36.546622,
        "longitude": 4.054898,
    },

    # ==================== ZONE E: AIT BOUADOU (8 stores) ====================
    {
        "email": "client.aitbouadou1@test.com",
        "full_name": "Ahmed Boudiaf",
        "phone": "0555205001",
        "store_name": "Superette Boudiaf",
        "role": UserRole.CUSTOMER,
        "h3_index": "8938749a8a7ffff",
        "address": "Centre, Ait Bouadou",
        "wilaya": "Tizi Ouzou",
        "daira": "Ouadhia",
        "commune": "Ait Bouadou",
        "latitude": 36.519247,
        "longitude": 4.066132,
    },
    {
        "email": "client.aitbouadou2@test.com",
        "full_name": "Kahina Yahi",
        "phone": "0555205002",
        "store_name": "Epicerie Yahi",
        "role": UserRole.CUSTOMER,
        "h3_index": "8938749a8a7ffff",
        "address": "Route Principale, Ait Bouadou",
        "wilaya": "Tizi Ouzou",
        "daira": "Ouadhia",
        "commune": "Ait Bouadou",
        "latitude": 36.521398,
        "longitude": 4.064769,
    },
    {
        "email": "client.aitbouadou3@test.com",
        "full_name": "Sabrina Hamdi",
        "phone": "0555205003",
        "store_name": "Mini Market Hamdi",
        "role": UserRole.CUSTOMER,
        "h3_index": "8938749a8a7ffff",
        "address": "Quartier Nord, Ait Bouadou",
        "wilaya": "Tizi Ouzou",
        "daira": "Ouadhia",
        "commune": "Ait Bouadou",
        "latitude": 36.517242,
        "longitude": 4.072370,
    },
    {
        "email": "client.aitbouadou4@test.com",
        "full_name": "Hakim Saidani",
        "phone": "0555205004",
        "store_name": "Alimentation Saidani",
        "role": UserRole.CUSTOMER,
        "h3_index": "8938749a8a7ffff",
        "address": "Quartier Sud, Ait Bouadou",
        "wilaya": "Tizi Ouzou",
        "daira": "Ouadhia",
        "commune": "Ait Bouadou",
        "latitude": 36.506560,
        "longitude": 4.059175,
    },
    {
        "email": "client.aitbouadou5@test.com",
        "full_name": "Samira Belhocine",
        "phone": "0555205005",
        "store_name": "Superette Belhocine",
        "role": UserRole.CUSTOMER,
        "h3_index": "8938749a8a7ffff",
        "address": "Place du Marché, Ait Bouadou",
        "wilaya": "Tizi Ouzou",
        "daira": "Ouadhia",
        "commune": "Ait Bouadou",
        "latitude": 36.507375,
        "longitude": 4.056735,
    },
    {
        "email": "client.aitbouadou6@test.com",
        "full_name": "Farid Ait Ahmed",
        "phone": "0555205006",
        "store_name": "Epicerie Ait Ahmed",
        "role": UserRole.CUSTOMER,
        "h3_index": "8938749a8a7ffff",
        "address": "Route de Boghni, Ait Bouadou",
        "wilaya": "Tizi Ouzou",
        "daira": "Ouadhia",
        "commune": "Ait Bouadou",
        "latitude": 36.511164,
        "longitude": 4.054709,
    },
    {
        "email": "client.aitbouadou7@test.com",
        "full_name": "Malika Idir",
        "phone": "0555205007",
        "store_name": "Mini Market Idir",
        "role": UserRole.CUSTOMER,
        "h3_index": "8938749a8a7ffff",
        "address": "Sortie Ouest, Ait Bouadou",
        "wilaya": "Tizi Ouzou",
        "daira": "Ouadhia",
        "commune": "Ait Bouadou",
        "latitude": 36.513596,
        "longitude": 4.038088,
    },
    {
        "email": "client.aitbouadou8@test.com",
        "full_name": "Nassim Cherifi",
        "phone": "0555205008",
        "store_name": "Alimentation Cherifi",
        "role": UserRole.CUSTOMER,
        "h3_index": "8938749a8a7ffff",
        "address": "Quartier Ouest, Ait Bouadou",
        "wilaya": "Tizi Ouzou",
        "daira": "Ouadhia",
        "commune": "Ait Bouadou",
        "latitude": 36.512701,
        "longitude": 4.045843,
    },

    # ==================== ZONE F: AIT MALEM / AIT KHELFA AREA (13 stores) ====================
    {
        "email": "client.aitmalem1@test.com",
        "full_name": "Hamid Ait Malem",
        "phone": "0555206001",
        "store_name": "Alimentation Ait Malem",
        "role": UserRole.CUSTOMER,
        "h3_index": "8938749a8a7ffff",
        "address": "Centre, Ait Malem",
        "wilaya": "Tizi Ouzou",
        "daira": "Ouadhia",
        "commune": "Ait Malem",
        "latitude": 36.538293,
        "longitude": 4.088375,
    },
    {
        "email": "client.aitmalem2@test.com",
        "full_name": "Said Bouzid",
        "phone": "0555206002",
        "store_name": "Epicerie Bouzid",
        "role": UserRole.CUSTOMER,
        "h3_index": "8938749a8a7ffff",
        "address": "Route Principale, Ait Malem",
        "wilaya": "Tizi Ouzou",
        "daira": "Ouadhia",
        "commune": "Ait Malem",
        "latitude": 36.529757,
        "longitude": 4.083192,
    },
    {
        "email": "client.aitmalem3@test.com",
        "full_name": "Lounis Mekhtoub",
        "phone": "0555206003",
        "store_name": "Superette Mekhtoub",
        "role": UserRole.CUSTOMER,
        "h3_index": "8938749a8a7ffff",
        "address": "Quartier Nord, Ait Malem",
        "wilaya": "Tizi Ouzou",
        "daira": "Ouadhia",
        "commune": "Ait Malem",
        "latitude": 36.533511,
        "longitude": 4.091767,
    },
    {
        "email": "client.aitkhelfa1@test.com",
        "full_name": "Mohand Ait Khelfa",
        "phone": "0555206004",
        "store_name": "Alimentation Ait Khelfa",
        "role": UserRole.CUSTOMER,
        "h3_index": "8938749a8a7ffff",
        "address": "Centre, Ait Khelfa",
        "wilaya": "Tizi Ouzou",
        "daira": "Ouadhia",
        "commune": "Ait Khelfa",
        "latitude": 36.522557,
        "longitude": 4.099510,
    },
    {
        "email": "client.aitkhelfa2@test.com",
        "full_name": "Rachid Oubraham",
        "phone": "0555206005",
        "store_name": "Mini Market Oubraham",
        "role": UserRole.CUSTOMER,
        "h3_index": "8938749a8a7ffff",
        "address": "Route Sud, Ait Khelfa",
        "wilaya": "Tizi Ouzou",
        "daira": "Ouadhia",
        "commune": "Ait Khelfa",
        "latitude": 36.511254,
        "longitude": 4.103063,
    },
    {
        "email": "client.aitkhelfa3@test.com",
        "full_name": "Belaid Ould Said",
        "phone": "0555206006",
        "store_name": "Epicerie Ould Said",
        "role": UserRole.CUSTOMER,
        "h3_index": "8938749a8a7ffff",
        "address": "Quartier Sud, Ait Khelfa",
        "wilaya": "Tizi Ouzou",
        "daira": "Ouadhia",
        "commune": "Ait Khelfa",
        "latitude": 36.500664,
        "longitude": 4.078865,
    },
    {
        "email": "client.aitkhelfa4@test.com",
        "full_name": "Yacine Ait Yahia",
        "phone": "0555206007",
        "store_name": "Superette Ait Yahia",
        "role": UserRole.CUSTOMER,
        "h3_index": "8938749a8a7ffff",
        "address": "Place du Village, Ait Khelfa",
        "wilaya": "Tizi Ouzou",
        "daira": "Ouadhia",
        "commune": "Ait Khelfa",
        "latitude": 36.503083,
        "longitude": 4.081106,
    },
    {
        "email": "client.aitkhelfa5@test.com",
        "full_name": "Tarik Meziani",
        "phone": "0555206008",
        "store_name": "Alimentation Meziani",
        "role": UserRole.CUSTOMER,
        "h3_index": "8938749a8a7ffff",
        "address": "Route de Ait Bouadou, Ait Khelfa",
        "wilaya": "Tizi Ouzou",
        "daira": "Ouadhia",
        "commune": "Ait Khelfa",
        "latitude": 36.520596,
        "longitude": 4.075607,
    },
    {
        "email": "client.aitkhelfa6@test.com",
        "full_name": "Nasser Boulahia",
        "phone": "0555206009",
        "store_name": "Mini Market Boulahia",
        "role": UserRole.CUSTOMER,
        "h3_index": "8938749a8a7ffff",
        "address": "Quartier Ouest, Ait Khelfa",
        "wilaya": "Tizi Ouzou",
        "daira": "Ouadhia",
        "commune": "Ait Khelfa",
        "latitude": 36.522058,
        "longitude": 4.071233,
    },
    {
        "email": "client.aitkhelfa7@test.com",
        "full_name": "Amar Ait Moussa",
        "phone": "0555206010",
        "store_name": "Epicerie Ait Moussa",
        "role": UserRole.CUSTOMER,
        "h3_index": "8938749a8a7ffff",
        "address": "Sortie Ouest, Ait Khelfa",
        "wilaya": "Tizi Ouzou",
        "daira": "Ouadhia",
        "commune": "Ait Khelfa",
        "latitude": 36.525840,
        "longitude": 4.073370,
    },
    {
        "email": "client.aitkhelfa8@test.com",
        "full_name": "Lamine Hadji",
        "phone": "0555206011",
        "store_name": "Superette Hadji",
        "role": UserRole.CUSTOMER,
        "h3_index": "8938749a8a7ffff",
        "address": "Route de Tizi N'Tlata, Ait Khelfa",
        "wilaya": "Tizi Ouzou",
        "daira": "Ouadhia",
        "commune": "Ait Khelfa",
        "latitude": 36.521483,
        "longitude": 4.064841,
    },
    {
        "email": "client.aitkhelfa9@test.com",
        "full_name": "Kamel Ould Ahmed",
        "phone": "0555206012",
        "store_name": "Alimentation Ould Ahmed",
        "role": UserRole.CUSTOMER,
        "h3_index": "8938749a8a7ffff",
        "address": "Quartier Nord-Ouest, Ait Khelfa",
        "wilaya": "Tizi Ouzou",
        "daira": "Ouadhia",
        "commune": "Ait Khelfa",
        "latitude": 36.526942,
        "longitude": 4.063852,
    },
    {
        "email": "client.aitkhelfa10@test.com",
        "full_name": "Omar Bensaid",
        "phone": "0555206013",
        "store_name": "Mini Market Bensaid",
        "role": UserRole.CUSTOMER,
        "h3_index": "8938749a8a7ffff",
        "address": "Sortie Sud, Ait Khelfa",
        "wilaya": "Tizi Ouzou",
        "daira": "Ouadhia",
        "commune": "Ait Khelfa",
        "latitude": 36.512126,
        "longitude": 4.061246,
    },

    # ==================== ZONE G: TEST CUSTOMERS (7 stores) ====================
    {
        "email": "test.customer1@test.com",
        "full_name": "Test Customer 1",
        "phone": "0555207001",
        "store_name": "Test Store 1",
        "role": UserRole.CUSTOMER,
        "h3_index": "893874c6143ffff",
        "address": "Test Location 1",
        "wilaya": "Tizi Ouzou",
        "daira": "Ouadhia",
        "commune": "Ouadhia",
        "latitude": 36.565509,
        "longitude": 4.111847,
    },
    {
        "email": "test.customer2@test.com",
        "full_name": "Test Customer 2",
        "phone": "0555207002",
        "store_name": "Test Store 2",
        "role": UserRole.CUSTOMER,
        "h3_index": "893874c6143ffff",
        "address": "Test Location 2",
        "wilaya": "Tizi Ouzou",
        "daira": "Ouadhia",
        "commune": "Ouadhia",
        "latitude": 36.563682,
        "longitude": 4.122158,
    },
    {
        "email": "test.customer3@test.com",
        "full_name": "Test Customer 3",
        "phone": "0555207003",
        "store_name": "Test Store 3",
        "role": UserRole.CUSTOMER,
        "h3_index": "893874c6143ffff",
        "address": "Test Location 3",
        "wilaya": "Tizi Ouzou",
        "daira": "Ouadhia",
        "commune": "Ouadhia",
        "latitude": 36.569590,
        "longitude": 4.125849,
    },
    {
        "email": "test.customer4@test.com",
        "full_name": "Test Customer 4",
        "phone": "0555207004",
        "store_name": "Test Store 4",
        "role": UserRole.CUSTOMER,
        "h3_index": "893874c6143ffff",
        "address": "Test Location 4",
        "wilaya": "Tizi Ouzou",
        "daira": "Ouadhia",
        "commune": "Ouadhia",
        "latitude": 36.571437,
        "longitude": 4.121656,
    },
    {
        "email": "test.customer5@test.com",
        "full_name": "Test Customer 5",
        "phone": "0555207005",
        "store_name": "Test Store 5",
        "role": UserRole.CUSTOMER,
        "h3_index": "893874c6143ffff",
        "address": "Test Location 5",
        "wilaya": "Tizi Ouzou",
        "daira": "Ouadhia",
        "commune": "Ouadhia",
        "latitude": 36.573353,
        "longitude": 4.128961,
    },
    {
        "email": "test.customer6@test.com",
        "full_name": "Test Customer 6",
        "phone": "0555207006",
        "store_name": "Test Store 6",
        "role": UserRole.CUSTOMER,
        "h3_index": "893874c6143ffff",
        "address": "Test Location 6",
        "wilaya": "Tizi Ouzou",
        "daira": "Ouadhia",
        "commune": "Ouadhia",
        "latitude": 36.571877,
        "longitude": 4.127354,
    },
    {
        "email": "test.customer7@test.com",
        "full_name": "Test Customer 7",
        "phone": "0555207007",
        "store_name": "Test Store 7",
        "role": UserRole.CUSTOMER,
        "h3_index": "893874c6143ffff",
        "address": "Test Location 7",
        "wilaya": "Tizi Ouzou",
        "daira": "Ouadhia",
        "commune": "Ouadhia",
        "latitude": 36.561314,
        "longitude": 4.125368,
    },

    # ==================== STAFF ====================
    {
        "email": "staff@test.com",
        "full_name": "Fatima Zohra Benali",
        "phone": "0555123421",
        "store_name": None,
        "role": UserRole.STAFF,
        "h3_index": "893874c6143ffff",
        "address": "Entrepot Elsuq, Ouadhia Centre",
        "wilaya": "Tizi Ouzou",
        "daira": "Ouadhia",
        "commune": "Ouadhia",
        "latitude": STORE_CENTER_LAT,
        "longitude": STORE_CENTER_LNG,
    },
]


def seed_test_users():
    """Seed the database with test users for development and testing."""
    logger.info("Starting test users seeding...")

    with Session(engine) as session:
        created_count = 0
        skipped_count = 0

        for user_data in TEST_USERS:
            # Check if user already exists
            existing_user = session.exec(
                select(User).where(User.email == user_data["email"])
            ).first()

            if existing_user:
                logger.info(f"User already exists: {user_data['email']} - skipping")
                skipped_count += 1
                continue

            # Extract driver and vehicle data if present
            driver_data = user_data.pop("driver_data", None)
            vehicle_data = user_data.pop("vehicle_data", None)

            # Create user
            user = User(
                email=user_data["email"],
                full_name=user_data["full_name"],
                phone=user_data["phone"],
                store_name=user_data.get("store_name"),
                role=user_data["role"],
                is_active=True,
                h3_index=user_data.get("h3_index"),
                address=user_data.get("address"),
                wilaya=user_data.get("wilaya"),
                daira=user_data.get("daira"),
                commune=user_data.get("commune"),
                latitude=user_data.get("latitude"),
                longitude=user_data.get("longitude"),
                auth_provider=AuthProvider.EMAIL,
                hashed_password=get_password_hash(DEFAULT_PASSWORD),
            )

            session.add(user)
            session.flush()  # Get user ID

            # Create driver and vehicle if this is a driver
            if driver_data and vehicle_data and user_data["role"] == UserRole.DRIVER:
                # Check if driver already exists for this user
                existing_driver = session.exec(
                    select(Driver).where(Driver.user_id == user.id)
                ).first()

                if existing_driver:
                    logger.info(f"Driver already exists for user {user.id} - skipping driver creation")
                else:
                    # Create driver
                    driver = Driver(
                        user_id=user.id,
                        status=driver_data["status"],
                        is_available=driver_data["is_available"],
                        max_active_orders=driver_data["max_active_orders"],
                    )
                    session.add(driver)
                    session.flush()  # Get driver ID

                    # Create vehicle
                    vehicle = DriverVehicle(
                        driver_id=driver.id,
                        vehicle_type=vehicle_data["vehicle_type"],
                        capacity_kg=vehicle_data["capacity_kg"],
                        capacity_volume=vehicle_data["capacity_volume"],
                        is_primary=True,
                    )
                    session.add(vehicle)
                    logger.info(f"Created driver with {vehicle_data['vehicle_type'].value} vehicle: {user.full_name}")
            else:
                logger.info(f"Created {user_data['role'].value}: {user.full_name}")

            created_count += 1

        session.commit()

    logger.info(f"Test users seeding completed! Created: {created_count}, Skipped: {skipped_count}")
    logger.info(f"Default password for all test users: {DEFAULT_PASSWORD}")

    # Print summary
    print("\n" + "="*60)
    print("TEST USERS CREATED - OUADHIA DAIRA, TIZI OUZOU")
    print("="*60)
    print(f"Password for all: {DEFAULT_PASSWORD}")
    print("-"*60)
    print("\nDRIVERS:")
    print("  - driver1@test.com - Chabane Melab (Truck, 30000kg) - Ouadhia")
    print("  - driver2@test.com - Youcef Mammeri (Van, 18000kg) - Agouni Gueghrane")
    print("  - driver3@test.com - Omar Hadj (Mini Van, 7000kg - Offline) - Ait Bouadou")
    print("\nCUSTOMERS BY ZONE:")
    print("  Zone A - Agouni Gueghrane: 9 stores")
    print("  Zone B - Ouadhia Centre: 20 stores")
    print("  Zone C - Tizi N'Tlata: 7 stores")
    print("  Zone D - Ait Bouadou: 8 stores")
    print("  Zone E - Ait Malem / Ait Khelfa: 13 stores")
    print("\nTOTAL: 57 stores + 3 drivers + 1 staff")
    print("\nSTAFF:")
    print("  - staff@test.com (Entrepot Ouadhia)")
    print("="*60 + "\n")


def delete_test_users():
    """Delete all test users (for cleanup)."""
    logger.info("Deleting test users...")

    with Session(engine) as session:
        for user_data in TEST_USERS:
            user = session.exec(
                select(User).where(User.email == user_data.get("email"))
            ).first()

            if user:
                # Driver and vehicles will be deleted via cascade
                session.delete(user)
                logger.info(f"Deleted user: {user_data.get('email')}")

        session.commit()

    logger.info("Test users deletion completed!")


if __name__ == "__main__":
    seed_test_users()
